### ISSUE TITLE
com/alibaba/wisp/timer/SleepTest.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#489]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147258?tab=1
```
configuration:
STDOUT:
ms = 6
interval = 110
ms = 63
interval = 173
ms = 66
interval = 172
ms = 73
interval = 173
STDERR:
java.lang.RuntimeException: Expected value to be true
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:395)
	at SleepTest.main(SleepTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
```

replay command:
```
test=jdk/test/com/alibaba/wisp/timer/SleepTest.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P $nproc bash -c "jtreg -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

复现概率：3/50

[33.log](https://github.com/alibaba/dragonwell8/files/10782401/33.log)
[20.log](https://github.com/alibaba/dragonwell8/files/10782402/20.log)
[14.log](https://github.com/alibaba/dragonwell8/files/10782403/14.log)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/19362139
