### ISSUE TITLE
-XX:-UseCompressedOops选项自研用例serviceability/sa/jmap-minidump/TestNoMinidumpAtFullGC.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#513]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/152376?tab=2

```log
Command line: [/opt/java/openjdk/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_test/classes/46/serviceability/sa/jmap-minidump:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/serviceability/sa/jmap-minidump:/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/46/testlibrary:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Xmx128m -Xms128m -XX:+HeapDumpBeforeFullGC TestNoMinidumpAtFullGC$OOMWorker ]
Command line: [/opt/java/openjdk/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_test/classes/46/serviceability/sa/jmap-minidump:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/serviceability/sa/jmap-minidump:/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/46/testlibrary:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Xmx128m -Xms128m -XX:+HeapDumpAfterFullGC TestNoMinidumpAtFullGC$OOMWorker ]
STDERR:
java.lang.RuntimeException: Expected that 104765499 > 104857600
	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:468)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
	at com.oracle.java.testlibrary.Asserts.assertGreaterThan(Asserts.java:250)
	at com.oracle.java.testlibrary.Asserts.assertGreaterThan(Asserts.java:238)
	at TestNoMinidumpAtFullGC.lambda$main$1(TestNoMinidumpAtFullGC.java:74)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at TestNoMinidumpAtFullGC.main(TestNoMinidumpAtFullGC.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
java.lang.RuntimeException: Failed
	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:468)
	at com.oracle.java.testlibrary.Asserts.fail(Asserts.java:444)
	at TestNoMinidumpAtFullGC.main(TestNoMinidumpAtFullGC.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
```

重跑未复现
```bash
test=hotspot/test/serviceability/sa/jmap-minidump/TestNoMinidumpAtFullGC.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 100 | xargs -i -n 1 -P $nproc bash -c "jtreg -XX:-UseCompressedOops -ea -esa -timeoutFactor:2 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

**Comment by sendaoYan** [comment]
重跑未复现，先关闭
