### ISSUE TITLE
8.16.17-Extended-Edition无法使用jrebel

### ISSUE THREAD

**Issue by glacier0315** [dragonwell-project/dragonwell8#597]
**Description**
8.15.16-Extended-Edition 可以正常使用jrebel，当升级到8.16.17-Extended-Edition，使用jreble 热部署就报错

/home/envy/dev/ide/JetBrains/ext/apache-tomcat-8/bin/catalina.sh run
[2023-09-25 03:27:12,397] 工件 WhgaEdu:war exploded: 正在等待服务器连接以启动工件部署…
JRebel-JVMTI [ERROR] FATAL ERROR in native method: processing of -agentpath failed
Exception in thread "main" java.lang.NoSuchFieldError: _jr$classLoaderStore
	at com.zeroturnaround.jrebelbase.VmAccess.getClassLoaderStore(SourceFile)
	at com.zeroturnaround.javarebel.abp.a(SourceFile:39)
	at com.zeroturnaround.javarebel.uy.a(SourceFile:56)
	at com.zeroturnaround.javarebel.uy.a(SourceFile:49)
	at com.zeroturnaround.javarebel.uy.registerURLClassLoader(SourceFile:24)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:41002)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1213)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1208)
	at java.lang.ClassLoader.getSystemResource(ClassLoader.java:1343)
	at com.zeroturnaround.javarebel.ji.a(SourceFile:10)
	at com.zeroturnaround.javarebel.iq.b(SourceFile:302)
	at com.zeroturnaround.javarebel.bu.b(SourceFile:148)
	at com.zeroturnaround.javarebel.hwx.a(SourceFile:332)
	at com.zeroturnaround.javarebel.hwy.run(SourceFile:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.zeroturnaround.javarebel.hwx.a(SourceFile:145)
	at com.zeroturnaround.reload.jvmti.MinimalInstrumentation.loadClassAndCallPremain(SourceFile:61)
已与服务器断开连接

**JDK version**
Alibaba_Dragonwell_Extended_8.16.17

**Execution environment**
 - OS and version: arch x64

**Comment by mysmlz** [comment]
+1
