### ISSUE TITLE
[upstream]compiler/rangechecks/RangeCheckEliminationScaleNotOne.java timeout with -Xcomp

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#619]
test command:
```bash
jtreg -va -nr -w tmp -Xcomp hotspot/test/compiler/rangechecks/RangeCheckEliminationScaleNotOne.java
```

result:
```
"main" #1 prio=5 os_prio=0 tid=0x00007f2c5400b000 nid=0x270c waiting on condition [0x00007f2c5bf65000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FilePermission.<init>(FilePermission.java:310)
        at sun.net.www.protocol.file.FileURLConnection.getPermission(FileURLConnection.java:225)
        at java.net.URLClassLoader.getPermissions(URLClassLoader.java:671)
        at sun.misc.Launcher$AppClassLoader.getPermissions(Launcher.java:360)
        at java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:206)
        - locked <0x00000005801537d8> (a java.util.HashMap)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        - locked <0x000000058015c190> (a java.lang.Object)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15609890
