### ISSUE TITLE
[dragonwell8][nightly][x64/aarch64]用例sun/security/x509/X509CRLImpl/UnexpectedNPE.java报错java.lang.AssertionError: Got unexpected exception ArrayIndexOutOfBoundsException instead of CRLException

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#638]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/314300
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/314299
【环境准备】

```
登录环境：
BINARY_URL=oss://compiler-ci-bucket/dragonwell8/CI/20240522-002906-056-#405-linux.aarch64.release.master-b17cf67c718a8f80164b68b4e47189048ddba576.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg5.1-b01.zip
JDK_REPO=https://github.com/dragonwell-project/dragonwell8.git
JDK_BRANCH=master
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_devb  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell8;tar -xf ${BINARY_URL##*/} -C bin-dragonwell8
cd bin-dragonwell8 && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo-dragonwell8

执行以下命令：
test="jdk-repo-dragonwell8/jdk/test/sun/security/x509/X509CRLImpl/UnexpectedNPE.java"
args="-Xmixed"
jtreg  -timeoutfactor:4 -nr -v:fail,error -w tmp  $args $native  $test
```
x64和aarch64都失败，本次验证以aarch64为准

【对比测试】
dragonwell8 release 没有问题
oss://dragonwell/8.19.20/Alibaba_Dragonwell_Standard_8.19.20_aarch64_linux.tar.gz

```
[dongzhichun@CompilerTest-aarch64-4 working]$ bin-d8-re/dragonwell-8.19.20/bin/java -version
openjdk version "1.8.0_412"
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition 8.19.20) (build 1.8.0_412-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition 8.19.20) (build 25.412-b01, mixed mode)
[dongzhichun@CompilerTest-aarch64-4 working]$ bin-d8-re/dragonwell-8.19.20/bin/java -Xinternalversion
OpenJDK 64-Bit Server VM (25.412-b01) for linux-aarch64 JRE (1.8.0_412-b01), built on May 10 2024 09:45:44 by "jenkins" with gcc 7.5.0
```
Temruin8 没有问题

```
[dongzhichun@CompilerTest-aarch64-4 working]$ bin-Tem/jdk8u412-b08/bin/java -version
openjdk version "1.8.0_412"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_412-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.412-b08, mixed mode)
[dongzhichun@CompilerTest-aarch64-4 working]$ bin-Tem/jdk8u412-b08/bin/java -Xinternalversion
OpenJDK 64-Bit Server VM (25.412-b08) for linux-aarch64 JRE (1.8.0_412-b08), built on Apr 17 2024 02:08:37 by "jenkins" with gcc 7.5.0
```
【用例日志】

```
STDERR:
java.lang.AssertionError: Got unexpected exception ArrayIndexOutOfBoundsException instead of CRLException
    at jdk.test.lib.Utils.lambda$runAndCheckException$3(Utils.java:627)
    at jdk.test.lib.Utils.runAndCheckException(Utils.java:645)
    at jdk.test.lib.Utils.runAndCheckException(Utils.java:616)
    at UnexpectedNPE.run(UnexpectedNPE.java:61)
    at UnexpectedNPE.main(UnexpectedNPE.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
    at java.lang.Thread.run(Thread.java:855)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at sun.security.pkcs.ContentInfo.<init>(ContentInfo.java:144)
    at sun.security.pkcs.PKCS7.parse(PKCS7.java:181)
    at sun.security.pkcs.PKCS7.parse(PKCS7.java:159)
    at sun.security.pkcs.PKCS7.<init>(PKCS7.java:136)
    at sun.security.provider.X509Factory.parseX509orPKCS7CRL(X509Factory.java:512)
    at sun.security.provider.X509Factory.engineGenerateCRLs(X509Factory.java:420)
    at java.security.cert.CertificateFactory.generateCRLs(CertificateFactory.java:535)
    at UnexpectedNPE.lambda$run$1(UnexpectedNPE.java:62)
    at jdk.test.lib.Utils.runAndCheckException(Utils.java:641)
    ... 9 more

JavaTest Message: Test threw exception: java.lang.AssertionError: Got unexpected exception ArrayIndexOutOfBoundsException instead of CRLException
JavaTest Message: shutting down test
```
【版本信息】

```
[dongzhichun@CompilerTest-aarch64-4 working]$ uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion
Linux CompilerTest-aarch64-4 5.10.134-16.1.al8.aarch64 #1 SMP Thu Dec 7 22:04:51 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          122Gi       1.1Gi       117Gi       2.0Mi       4.3Gi       120Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               0
Model name:          Neoverse-N2
Stepping:            r0p0
CPU MHz:             3000.000
CPU max MHz:         3000.0000
CPU min MHz:         3000.0000
BogoMIPS:            100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            65536K
NUMA node0 CPU(s):   0-31
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.18.19) (build 1.8.0_372-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.18.19) (build 25.372-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.372-b01) for linux-aarch64 JRE (1.8.0_372-b01), built on May 21 2024 16:31:43 by "" with gcc 4.8.5 20150623 (Red Hat 4.8.5-44)
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/16778498
