### ISSUE TITLE
sun/management/HotspotRuntimeMBean/GetTotalSafepointTime.java intermittent fails

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#684]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/371183

```
java.lang.RuntimeException: Total safepoint time illegal value: 0 ms (MIN = 1; MAX = 9223372036854775807)
	at GetTotalSafepointTime.main(GetTotalSafepointTime.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8228658

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk8u-dev/pull/578
