### ISSUE TITLE
[upstream]jdk/jfr/event/runtime/TestThrowableInstrumentation.java intermittent fails

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#692]
job:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/396980?tab=1

```
STDOUT:
Started recording 1. No limit specified, using maxsize=250MB as default.

Use jcmd 1694413 JFR.dump name=1 filename=FILEPATH to copy recording data to file.
Warning: 'NoSuchMethodError' on register of sun.hotspot.WhiteBox::NMTNewArena(J)J
Warning: 'NoSuchMethodError' on register of sun.hotspot.WhiteBox::NMTFreeArena(J)V
Warning: 'NoSuchMethodError' on register of sun.hotspot.WhiteBox::NMTArenaMalloc(JJ)V
Warning: 'NoSuchMethodError' on register of sun.hotspot.WhiteBox::validateCgroup(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
WB error: failed to compile at level 1 method  java.lang.Throwable::<clinit>
STDERR:
java.lang.RuntimeException: Unable to compile Throwable::<clinit> with C1
	at jdk.jfr.event.runtime.TestThrowableInstrumentation.main(TestThrowableInstrumentation.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)
```
[TestThrowableInstrumentation.java.log](https://github.com/user-attachments/files/17611000/TestThrowableInstrumentation.java.log)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/18999879

**Comment by sendaoYan** [comment]
主干没有问题 https://tone.aliyun-inc.com/ws/xesljfzh/test_result/397273
