### ISSUE TITLE
-XX:TieredStopAtLevel=1选项compiler/8009761/Test8009761.java报错java.lang.RuntimeException: static java.lang.Object Test8009761.m3(boolean,boolean) not compiled

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#697]
<https://tone.aliyun-inc.com/ws/xesljfzh/test_result/401069>   
【环境准备】

```
BINARY_URL=oss://dragonwell/8.23.22-test-dragonwell_standard/Alibaba_Dragonwell_Standard_8.23.22_x64_linux.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg5.1-b01.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell8.git
JDK_BRANCH=dragonwell_standard-8.23.22
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell8;tar -xf ${BINARY_URL##*/} -C bin-dragonwell8

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo-dragonwell8

执行以下命令：
cd bin-dragonwell8/dragonwell-8.20.21/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

jtreg  -nr -v:fail,error -w tmp  -XX:TieredStopAtLevel=1  jdk-repo-dragonwell8/hotspot/test/compiler/8009761/Test8009761.java
```
【测试分析】  
x64和aarch64都有问题  

【对比分析】  
dragonwell8 release 没问题  
oss://dragonwell/8.20.21/Alibaba_Dragonwell_Standard_8.20.21_x64_linux.tar.gz    

Temruin8 同样问题  
oss://compiler-ci-bucket/openjdk/jdk8u432-ga/OpenJDK8U-jdk_x64_linux_hotspot_8u432b06.tar.gz   

【用例日志】

```
STDOUT:
CompilerOracle: exclude Test8009761.m2
### Excluding compile: static Test8009761::m2
WB error: invalid compilation level 4
STDERR:
java.lang.RuntimeException: static java.lang.Object Test8009761.m3(boolean,boolean) not compiled
	at Test8009761.main(Test8009761.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: static java.lang.Object Test8009761.m3(boolean,boolean) not compiled
JavaTest Message: shutting down test
```
【jdk版本】

```
 java -version;java -Xinternalversion
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition 8.20.21) (build 1.8.0_422-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition 8.20.21) (build 25.422-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.422-b01) for linux-amd64 JRE (1.8.0_422-b01), built on Nov  8 2024 23:52:22 by "root" with gcc 7.5.0
```
【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux CompilerTest-x64-4 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       1.6Gi       106Gi       2.0Mi        15Gi       120Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Stepping:            6
CPU MHz:             3528.270
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
```

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8048003
