### ISSUE TITLE
[dragonwell8][release/fastdebug][nightly]com/alibaba/wisp/timer/SleepTest.java随机报错java.lang.Error: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#707]
<https://tone.aliyun-inc.com/ws/xesljfzh/test_result/416898>    
<https://tone.aliyun-inc.com/ws/xesljfzh/test_result/416899>     
【环境准备】

```
BINARY_URL=oss://compiler-ci-bucket/dragonwell8/CI/tar/20241128-002916-210-#629-linux.x86_64.release.master-fc526cfc6ed595b6b6c24113aae6c989ab5b1e13.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg5.1-b01.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell8.git
JDK_BRANCH=master
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell8;tar -xf ${BINARY_URL##*/} -C bin-dragonwell8

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo

执行以下命令：
cd bin-dragonwell8/j2sdk-image/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

jtreg  -nr -v:fail,error -w tmp  -Xmixed jdk-repo/jdk/test/com/alibaba/wisp/timer/SleepTest.java
```
【测试分析】    
release、fastdebug的aarch64、x86_64都有问题，失败率1/20，复现命令

```
function runJtreg() { jtreg $args  -Xmixed -J-Djavatest.maxOutputSize=999999999  -timeoutFactor:4 -v:fail,error,time -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ;else rm -rf $dir/index-$1 $dir/$1.log;fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java | sed "s|#|_|"` ; rm -rf $dir ; mkdir -p $dir ; time seq 20 | xargs -i -n 1 -P 10 bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
20
real    0m5.606s
user    1m4.462s
sys     0m9.380s
total fail number: 1

```
【对比测试】   

```
dragonwell8 release   同样问题  
oss://dragonwell/8.23.22-test-dragonwell_extended/Alibaba_Dragonwell_Extended_8.23.22_x64_linux.tar.gz  

Temurin8    不涉及
```

【用例日志】

```
STDERR:
java.lang.Error: java.util.concurrent.TimeoutException
        at SleepTest.lambda$main$1(SleepTest.java:51)
        at java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119)
        at java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:89)
        at java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:162)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:306)
        at java.util.stream.MatchOps$MatchTask.doLeaf(MatchOps.java:277)
        at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:242)
        at java.util.stream.MatchOps$MatchOp.evaluateParallel(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.allMatch(IntPipeline.java:506)
        at SleepTest.main(SleepTest.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at SleepTest.lambda$main$1(SleepTest.java:49)
        ... 24 more

JavaTest Message: Test threw exception: java.lang.Error: java.util.concurrent.TimeoutException
JavaTest Message: shutting down test

```
【jdk版本】

```
java -version;java -Xinternalversion
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.20.21) (build 1.8.0_372-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.20.21) (build 25.372-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.372-b01) for linux-amd64 JRE (1.8.0_372-b01), built on Nov 27 2024 16:42:36 by "" with gcc 4.8.2 20140120 (Red Hat 4.8.2-15)
```
【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux CompilerTest-x64-3 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       1.3Gi       116Gi       2.0Mi       5.7Gi       121Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Stepping:            6
CPU MHz:             3533.136
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/19507062
